BPS Leader Code Structure
lhr-solar/BPS-Leader pull request #2
Opened 2024-11-06 23:05 UTC by Lakshay983

2025-01-27 18:34 UTC, IshDeshpa requested changes
baah

2025-01-27 18:34 UTC, IshDeshpa commented on Apps/Src/main.c
> +   );
we don't need an init task you can just do all the initialization in main and then launch ur actual tasks. i think this was a micrium specific thing.

2025-01-27 18:34 UTC, IshDeshpa commented on Drivers/Src/LEDs.c
> +    }
what is this do a switch statement or ifdefs

2025-01-27 18:34 UTC, IshDeshpa commented on Drivers/Src/LEDs.c
> +    }
you could even do a macro concat to take the value of HEARTBEATPORT and put it in the middle of __HAL_RCC_*_CLK_ENABLE

2025-01-27 18:34 UTC, IshDeshpa commented on Config/Src/config_msgs.c
> +#pragma message(PRE("⚡") "NUM_BATTERY_MODULES set to                " XSTR(NUM_BATTERY_MODULES))
emojis in the code? disgusting

2025-01-27 18:34 UTC, IshDeshpa commented on Makefile
> +PROJECT_BUILD_DIR = Objects
I don't really like the old style of naming things. But it doesn't matter. Just wanted to express that.

2025-01-27 18:34 UTC, IshDeshpa commented on Tasks/Src/InitTask.c
> +        &Task_Voltage_Buffer  /* Buffer for static allocation. */
as said above lowk you can just put this in main

2025-01-27 19:27 UTC, Lakshay983 commented on Apps/Src/main.c
> +   );
you need to do the BSP inits in a task right? So for stuff like BSP_CAN I need to init that in a task, or should I just call BSP_CAN_Init() across different tasks

2025-01-27 19:28 UTC, Lakshay983 commented on Makefile
> +PROJECT_BUILD_DIR = Objects
Ok, I'll rename it to match Embedded-Sharepoint's

2025-01-27 21:41 UTC, IshDeshpa commented on Apps/Src/main.c
> +   );
just call it in the init task it's fine. i forgot you need the OS initialized before BSP initialization for the critical section stuff

2025-02-01 17:02 UTC, Lakshay983 commented on Drivers/Src/LEDs.c
> +    }
cringe

2025-02-06 19:48 UTC, IshDeshpa commented on Drivers/Src/LEDs.c
> +        __HAL_RCC_GPIOE_CLK_ENABLE();
switch statement

2025-02-06 19:49 UTC, IshDeshpa approved these changes
switch statement

2025-02-07 16:23 UTC, merged